#!/usr/bin/bash
# bash script for certain softwares for Ezy Lb

sudo apt-get update
sudo apt install -y net-tools
sudo apt install -y  haproxy
sudo apt install -y certbot
sudo apt-get -y install software-properties-common
sudo systemctl restart haproxy
