CREATE TABLE admin (
    id VARCHAR(100) PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    username VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(300) NOT NULL,
    login_time JSON DEFAULT NULL,
    logout_time JSON DEFAULT NULL,
    two_factor VARCHAR(50) NOT NULL,
    two_factor_status VARCHAR(15) DEFAULT 'enabled',
    rights VARCHAR(255) DEFAULT 'GET'
);
